export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SAVE_SHIPPING_ADDRESS_CART = "SAVE_SHIPPING_ADDRESS_CART";
export const SAVE_PAYMENT_METHOD_CART = "SAVE_PAYMENT_METHOD_CART";
